# vim:foldmethod=marker:
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
	" Dein Clearn
	function! s:dein_clean() abort
		let s:plugins = dein#check_clean()
		if !empty(s:plugins)
			echo s:plugins
			call map(s:plugins, "delete(v:val, 'rf')")
			call dein#recache_runtimepath()
		endif
	endfunction
	command! DeinClean call s:dein_clean()

	" Dein List
	" https://koturn.hatenablog.com/entry/2016/09/01/050000
	function! s:dein_list() abort
		echomsg '[dein] #: not sourced, X: not installed'
		for pair in items(dein#get())
			echomsg (!isdirectory(pair[1].path) ? 'X'
					\ : pair[1].sourced ? ' '
					\ : '#') pair[0]
		endfor
	endfunction
	command! DeinList call s:dein_list()
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
autocmd MyAutoCmd VimEnter * nested colorscheme iceberg
'''

# ------

[[plugins]] # 折りたたみを改善
repo = 'LeafCage/foldCC.vim'
hook_add = '''
	if &filetype !=# 'help'
		setlocal foldtext=FoldCCtext()
	endif
'''

[[plugins]] # 対応括弧のハイライトを改善
repo = 'itchyny/vim-parenmatch'
hook_add = '''
	let g:loaded_matchparen = v:true
'''

# ------

[[plugins]]
repo = 'sheerun/vim-polyglot'
merged = 'v:false'
hook_add = '''
let g:polyglot_disabled = ['markdown']
'''

[[plugins]] # vim
repo = 'vim-jp/syntax-vim-ex'

[[plugins]] # zsh
repo = 'chrisbra/vim-zsh'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja,en'

# ------

[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'Shougo/deoplete-nextword'
if = 'executable("nextword")'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'ujihisa/neco-look'
if = 'executable("look")'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
if = 'executable("ghq")'
on_source = 'denite.nvim'
