[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # dein.vim command
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

# EditorConfig {{{
#[[plugins]]
#repo = 'editorconfig/editorconfig-vim'
#if = 'executable("editorconfig")'
#on_path = '.*'
#hook_source = '''
#	let g:EditorConfig_core_mode = 'external_command'
#
#	if dein#tap('gina.vim')
#		let g:EditorConfig_exclude_patterns = ['gina://.*']
#	endif
#'''

[[plugins]]
repo = 'rakus/vimscript-editorconfig'
on_path = '.*'
# }}}
# motion {{{

[[plugins]] # 上下移動改善
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>(accelerated'}
hook_add = '''
	nmap j <Plug>(accelerated_jk_gj)
	nmap k <Plug>(accelerated_jk_gk)
'''

[[plugins]] # Edge motion
repo = 'haya14busa/vim-edgemotion'
on_map = '<Plug>(edgemotion-'
hook_add = '''
	map <C-j> <Plug>(edgemotion-j)
	map <C-k> <Plug>(edgemotion-k)
'''

[[plugins]] # word単位の移動改善
repo = 'kana/vim-smartword'
on_map = {n = '<Plug>(smartword-'}
hook_add = '''
	nmap w <Plug>(smartword-w)
	nmap b <Plug>(smartword-b)
	nmap e <Plug>(smartword-e)
'''

[[plugins]]
repo = 'terryma/vim-expand-region'
on_map = {v = '<Plug>(expand'}
hook_add = '''
    vmap v <Plug>(expand_region_expand)
    vmap <C-v> <Plug>(expand_region_shrink)
'''

# }}}
