[[plugins]] # Lib
repo = 'Shougo/context_filetype.vim'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja,en'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
	let g:polyglot_disabled = ['markdown', 'css']
'''

[[plugins]] # CSS3
repo = 'hail2u/vim-css3-syntax'

# Markdown {{{

[[plugins]] # GitHub Flavored Markdown
repo = 'rhysd/vim-gfm-syntax'
on_ft = 'markdown'
hook_source = '''
	let g:markdown_fenced_languages = [
	\	'html',
	\	'css',
	\	'scss',
	\	'javascript',
	\	'js=javascript',
	\	'yaml',
	\	'toml',
	\	'zsh',
	\]
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
hook_post_update = '!cd app && ./install.sh'
on_cmd = 'MarkdownPreview'
on_ft = ["markdown", "pandoc.markdown", "rmd"]

# }}}

[[plugins]] # vim
repo = 'vim-jp/syntax-vim-ex'

[[plugins]] # zsh
repo = 'chrisbra/vim-zsh'
